# Generated by Django 4.2.13 on 2024-06-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0005_service_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.dentist')),
            ],
        ),
    ]
