# Generated by Django 4.2.13 on 2024-06-09 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_appointmentrequest_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmentrequest',
            unique_together=set(),
        ),
    ]
