# Generated by Django 4.2.13 on 2024-06-09 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointmentrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='user',
        ),
    ]
