# Generated by Django 4.2.13 on 2024-06-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_remove_appointmentrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
