# Generated by Django 4.2.13 on 2024-06-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointmentrequest_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='full_name',
            field=models.CharField(default='Please enter your name', max_length=200),
        ),
    ]
