# Generated by Django 4.2.13 on 2024-06-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200)),
                ('services', models.ManyToManyField(related_name='dentists', to='clinic.service')),
            ],
        ),
    ]
