# Generated by Django 4.2.13 on 2024-06-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_dentist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='name',
        ),
    ]
