# Generated by Django 4.2.13 on 2024-06-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_contactformrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformrequest',
            name='email',
            field=models.EmailField(default='Enter your email', max_length=254),
        ),
    ]
